/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.aaa_componentes;

import java.awt.Color;
import java.io.Serializable;
import java.time.LocalDate;

/**
 *
 * @author Alejandro
 */
public class NewJPanel extends javax.swing.JFrame implements Serializable {
    private int mes = LocalDate.now().getMonthValue();
    private int ano = LocalDate.now().getYear();  
    private int m;
    private int a; 
    private int cvc;  
    private JDNIField dni;
    private String dniValidar;
    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnValidar = new javax.swing.JButton();
        jTFTargeta = new javax.swing.JTextField();
        lbl3 = new javax.swing.JLabel();
        jTFMes = new javax.swing.JTextField();
        jTFAno = new javax.swing.JTextField();
        jDNIField1 = new com.mycompany.aaa_componentes.JDNIField();
        jLabel4 = new javax.swing.JLabel();
        jTFCvc = new javax.swing.JTextField();

        jLabel1.setText("Introduzca el numero de la tarjeta: ");

        jLabel3.setText("Fecha de Caducidad: ");

        jLabel2.setText("Introduzca el DNI: ");

        btnValidar.setText("Validar");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });

        lbl3.setText(" /");

        jTFMes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFMesFocusLost(evt);
            }
        });

        jTFAno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFAnoFocusLost(evt);
            }
        });

        jDNIField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jDNIField1FocusLost(evt);
            }
        });

        jLabel4.setText("CVC: ");

        jTFCvc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFCvcFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFTargeta, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                                    .addComponent(jDNIField1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jTFMes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTFAno, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jTFCvc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnValidar)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFTargeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFMes, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFAno, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFCvc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDNIField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(btnValidar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        validarFecha();
        validarCVC();        
        dni.validateDNI(dniValidar);
    }//GEN-LAST:event_btnValidarActionPerformed

    private void jTFMesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFMesFocusLost
        try {            
            m = Integer.valueOf(jTFMes.getText());
        }catch (Exception e) {
            
        }
    }//GEN-LAST:event_jTFMesFocusLost

    private void jTFAnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFAnoFocusLost
        try {            
            this.a = Integer.valueOf(jTFAno.getText());
        }catch (Exception e) {
            
        }
    }//GEN-LAST:event_jTFAnoFocusLost

    private void jTFCvcFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFCvcFocusLost
        try {            
            this.cvc = Integer.valueOf(jTFCvc.getText());
        }catch (Exception e) {
            
        }
    }//GEN-LAST:event_jTFCvcFocusLost

    private void jDNIField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jDNIField1FocusLost
        dniValidar = jDNIField1.getText();
    }//GEN-LAST:event_jDNIField1FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NewJPanel().setVisible(true);
            }
        });
    }
    
    public boolean validarFecha() {
        boolean validado = false;
        if (validarAno() && validarMes() ){
            if (ano <= a) {
                if (mes <= m) {
                    validado = true;
                    jTFMes.setForeground(Color.green); 
                    jTFAno.setForeground(Color.green); 
                    
                }
                
                else {
                    jTFMes.setForeground(Color.red);
                    jTFAno.setForeground(Color.red); 
                } 
            }
            else {
                jTFMes.setForeground(Color.red);
                jTFAno.setForeground(Color.red); 
            }
        }
        
            return validado;
    }
    
    private boolean validarMes() {
        boolean mesValido = false;
        
        if(m <= 12) {
            mesValido = true;
        }
        return mesValido;
    }
    
    private boolean validarAno() {
        boolean anoValido = false;
        
        if(a >= 2020 && a < 2050) {
            anoValido = true;
        }
        return anoValido;
    }
    
    public boolean validarCVC() {
        boolean cvcValido = false;
        
        if(cvc > 99 && cvc < 999) {
            cvcValido = true;
        }
        return cvcValido;
    }
        
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnValidar;
    private com.mycompany.aaa_componentes.JDNIField jDNIField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTFAno;
    private javax.swing.JTextField jTFCvc;
    private javax.swing.JTextField jTFMes;
    private javax.swing.JTextField jTFTargeta;
    private javax.swing.JLabel lbl3;
    // End of variables declaration//GEN-END:variables
}
